services:
  - type: web
    name: pivision-bridge
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PI_USER
        value: tanda.abt1
      - key: PI_PASS
        value: ntpc@123
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
